apiVersion: batch/v1
kind: CronJob
metadata:
  name: metrics-collector
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: metrics-collector
            image: gaurir211/assignment:017
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: metrics-volume
              mountPath: /metrics
          restartPolicy: OnFailure
          volumes:
          - name: metrics-volume
            persistentVolumeClaim:
              claimName: myclaim
